# Generated by Django 4.2.5 on 2023-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Aguardando'), (1, 'Pago'), (2, 'Cancelado'), (3, 'Recusado')], default=0, verbose_name='Status')),
                ('url', models.URLField(verbose_name='Url')),
                ('divido', models.IntegerField(choices=[(1, '1x sem juros'), (2, '2x sem juros'), (3, '3x sem juros')], default=1, verbose_name='Status')),
            ],
        ),
    ]
