# Generated by Django 4.2.5 on 2023-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpagamento',
            name='divido',
        ),
        migrations.AddField(
            model_name='linkpagamento',
            name='dividir',
            field=models.IntegerField(choices=[(1, '1x sem juros'), (2, '2x sem juros'), (3, '3x sem juros')], default=1, verbose_name='Em até'),
        ),
    ]
