# Generated by Django 4.2.5 on 2023-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='endereco_entrega',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='informacoes',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='payment_motoboy',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='payment_pedido',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
