# Generated by Django 4.2.5 on 2023-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='valor_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
