# Generated by Django 4.2.5 on 2023-10-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0002_alter_entrega_valor_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
