# Generated by Django 4.2.5 on 2023-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0002_remove_entrega_endereco_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='informacoes',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='payment_motoboy',
            field=models.IntegerField(choices=[(0, 'Pedente'), (1, 'Pago')], default=0),
        ),
        migrations.AddField(
            model_name='entrega',
            name='payment_pedido',
            field=models.IntegerField(choices=[(0, 'Pedente'), (1, 'Pago')], default=0),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Saiu para entrega'), (2, 'Entregue')], default=0),
        ),
    ]
