# Generated by Django 4.2.5 on 2023-09-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0005_alter_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='pedido_numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Pedido nº'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Cep'),
        ),
    ]
