# Generated by Django 4.2.5 on 2023-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreteApp', '0006_entrega_pedido_numero_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='payment_motoboy',
            field=models.IntegerField(choices=[(0, 'Pedente'), (1, 'Pago')], default=0, verbose_name='M.pago'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='payment_pedido',
            field=models.IntegerField(choices=[(0, 'Pedente'), (1, 'Pago')], default=0, verbose_name='P.pago'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Saiu para entrega'), (2, 'Entregue')], default=0, verbose_name='Status'),
        ),
    ]
